### ISSUE TITLE
Treat BVH animation data as an asset and create an asset loader for it

### ISSUE THREAD

**Issue by nixon-voxell** [kahboon0425/bevy_motion_matching#16]
## The Idea

At the moment, BVH data is loaded and stored inside a Bevy resource struct as a list:
```rust
#[derive(Resource)]
pub struct BvhData {
    pub bvh_animation: Vec<Bvh>,
}
```
This approach left developers unable to reference a unique `Bvh` animation without risking the chances of it being removed or moved as the only approach right now is to store the index of that `Bvh` animation.

### Example

During runtime, an index might be used to reference a specific `Bvh` animation in the `bvh_animation` list:
```rust
let index = None;
for i in 0..bvh_animation.len() {
    // find specific bvh animation
    if xxx == yyy {
        index = Some(i);
        break;
    }
}
```
The specific `index` that is being extracted might not stay true if something like this happen during runtime:
```rust
bvh_animation.insert(0, new_bvh);
```
This is a hypothetical situation that may or may not happen for whatever reason, but knowing that such a simple innocent `insert` operation might cause a seemingly untraceable bug is mind-boggling!

## Proposed Solution

We treat every `Bvh` animation as an asset ([a simplified sample](https://github.com/nixon-voxell/bevy_vello_renderer/blob/main/src/vello_scene.rs#L28-L31)). Instead of storing indices pointing to a specific animation, we use Bevy's asset [`Handle<T>`](https://github.com/nixon-voxell/bevy_vello_renderer/blob/main/src/vello_scene.rs#L15) system.

This will guarantee us a unique pointer towards the `Bvh` animation asset and tell us when it is missing.

Bevy `Handle<T>` doc: https://docs.rs/bevy/latest/bevy/prelude/enum.Handle.html
Bevy `Assets` doc:
- https://docs.rs/bevy/latest/bevy/asset/struct.Assets.html
- https://docs.rs/bevy/latest/bevy/asset/index.html

**Comment by ConquerorFY** [comment]
Can check out branch and see
